# Form implementation generated from reading ui file 'ExportProgressDlg.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExportProgressDlg(object):
    def setupUi(self, ExportProgressDlg):
        ExportProgressDlg.setObjectName("ExportProgressDlg")
        ExportProgressDlg.resize(385, 85)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExportProgressDlg.sizePolicy().hasHeightForWidth())
        ExportProgressDlg.setSizePolicy(sizePolicy)
        ExportProgressDlg.setMinimumSize(QtCore.QSize(385, 85))
        ExportProgressDlg.setMaximumSize(QtCore.QSize(385, 85))
        self.verticalLayout = QtWidgets.QVBoxLayout(ExportProgressDlg)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout.setContentsMargins(6, 6, 6, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(parent=ExportProgressDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(370, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(370, 16777215))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ExportProgressDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(ExportProgressDlg)
        self.buttonBox.accepted.connect(ExportProgressDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(ExportProgressDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExportProgressDlg)

    def retranslateUi(self, ExportProgressDlg):
        _translate = QtCore.QCoreApplication.translate
        ExportProgressDlg.setWindowTitle(_translate("ExportProgressDlg", "Export Progress"))
