# Form implementation generated from reading ui file 'HelpDlg.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HelpDlg(object):
    def setupUi(self, HelpDlg):
        HelpDlg.setObjectName("HelpDlg")
        HelpDlg.resize(706, 542)
        HelpDlg.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(HelpDlg)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=HelpDlg)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=HelpDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(HelpDlg)
        self.buttonBox.accepted.connect(HelpDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(HelpDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HelpDlg)

    def retranslateUi(self, HelpDlg):
        _translate = QtCore.QCoreApplication.translate
        HelpDlg.setWindowTitle(_translate("HelpDlg", "xPyScript Help"))
