# Form implementation generated from reading ui file 'NewSequenceDlg.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewSequenceDlg(object):
    def setupUi(self, NewSequenceDlg):
        NewSequenceDlg.setObjectName("NewSequenceDlg")
        NewSequenceDlg.resize(455, 125)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewSequenceDlg.sizePolicy().hasHeightForWidth())
        NewSequenceDlg.setSizePolicy(sizePolicy)
        NewSequenceDlg.setMinimumSize(QtCore.QSize(455, 125))
        NewSequenceDlg.setMaximumSize(QtCore.QSize(455, 125))
        self.verticalLayout = QtWidgets.QVBoxLayout(NewSequenceDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=NewSequenceDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit1 = QtWidgets.QLineEdit(parent=NewSequenceDlg)
        self.lineEdit1.setEnabled(True)
        self.lineEdit1.setReadOnly(True)
        self.lineEdit1.setObjectName("lineEdit1")
        self.gridLayout.addWidget(self.lineEdit1, 0, 1, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(parent=NewSequenceDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton1.sizePolicy().hasHeightForWidth())
        self.pushButton1.setSizePolicy(sizePolicy)
        self.pushButton1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=NewSequenceDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit2 = QtWidgets.QLineEdit(parent=NewSequenceDlg)
        self.lineEdit2.setReadOnly(True)
        self.lineEdit2.setObjectName("lineEdit2")
        self.gridLayout.addWidget(self.lineEdit2, 1, 1, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(parent=NewSequenceDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton2.sizePolicy().hasHeightForWidth())
        self.pushButton2.setSizePolicy(sizePolicy)
        self.pushButton2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NewSequenceDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.lineEdit1)
        self.label_2.setBuddy(self.lineEdit2)

        self.retranslateUi(NewSequenceDlg)
        self.buttonBox.accepted.connect(NewSequenceDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(NewSequenceDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewSequenceDlg)
        NewSequenceDlg.setTabOrder(self.lineEdit1, self.pushButton1)
        NewSequenceDlg.setTabOrder(self.pushButton1, self.lineEdit2)
        NewSequenceDlg.setTabOrder(self.lineEdit2, self.pushButton2)

    def retranslateUi(self, NewSequenceDlg):
        _translate = QtCore.QCoreApplication.translate
        NewSequenceDlg.setWindowTitle(_translate("NewSequenceDlg", "New Sequence"))
        self.label.setText(_translate("NewSequenceDlg", "Sequence name:"))
        self.pushButton1.setText(_translate("NewSequenceDlg", "..."))
        self.label_2.setText(_translate("NewSequenceDlg", "xLights model:"))
        self.pushButton2.setText(_translate("NewSequenceDlg", "..."))
